process.env.NODE_ENV = "test";
process.env.JWT_SECRET = process.env.JWT_SECRET || "test_secret_value_with_at_least_32_chars";
process.env.JWT_EXPIRES_IN = process.env.JWT_EXPIRES_IN || "7d";
process.env.BCRYPT_SALT_ROUNDS = process.env.BCRYPT_SALT_ROUNDS || "10";
process.env.CORS_ORIGIN = process.env.CORS_ORIGIN || "http://localhost:5173";
process.env.APP_NAME = process.env.APP_NAME || "BJOC Backend";
process.env.EMAIL_USER = process.env.EMAIL_USER || "test@example.com";
process.env.EMAIL_PASS = process.env.EMAIL_PASS || "test-password";
process.env.DATABASE_URL = process.env.DATABASE_URL || "postgresql://postgres:postgres@localhost:5432/postgres";
